project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc: true
    toc-location: left
    title-block-style: manuscript
  docx: default
  jats: default
  agu-pdf: default

execute:
  freeze: true

editor: visual

